### ISSUE TITLE
【Bug】LoadScene相关的事件，消息没有正确发出

### ISSUE THREAD

**Issue by JaeyJiang** [GameFrameX/GameFrameX.Unity#10]
![LF1AY3Y3OFFAE17L%`K LFV](https://github.com/user-attachments/assets/df4ee668-38db-43c3-9b77-078c3c5052ee)

LoadScene()

监听了,加载场景成功了没有反应

**Comment by AlianBlank** [comment]
LoadSceneUpdateEventArgs 这个暂时获取不到.因为YooAsset没有这个接口返回
