### ISSUE TITLE
UGUI多次生成实体

### ISSUE THREAD

**Issue by LiuLangTianYa** [GameFrameX/GameFrameX.Unity#11]
UGUI 生成的时候，如果走的是bundles的路径，会生成两次实体
![1730687405426](https://github.com/user-attachments/assets/90792a45-d931-4c6d-82d4-925cefece361)
![Quicker_20241104_103145](https://github.com/user-attachments/assets/c3d05437-eabc-4e43-be1b-4dc35adfb151)

**Comment by LiuLangTianYa** [comment]
![LoginUI生成代码](https://github.com/user-attachments/assets/1c6bb814-59f5-457a-b9fb-b2bc8879759e)

**Comment by LiuLangTianYa** [comment]
hello，啥时候考虑解决下这个问题啊

**Comment by AlianBlank** [comment]
已修复,

1. 现在已经增加自动生成代码的功能。

- 第一步需要创建一个预制体。然后在其右键点击生成代码菜单

![image](https://github.com/user-attachments/assets/7901edb8-1c78-49d3-9aaa-163803a3ff8a)

- 第二步需要点击一下重新绑定列表的按钮。将会自动寻找对应的组件绑定到代码上

![image](https://github.com/user-attachments/assets/36dae794-1fc2-422e-a897-007b2aa3de2b)

2. 和按钮的事件绑定扩展函数
为了和FGUI的调用接口一致。增加以下几个函数的语法糖
- Add 绑定按钮回调函数
- Remove 移除按钮回调函数
- Set 先移除所有的回调函数，然后绑定一个新的回调函数
- Clear 清空所有已经绑定的回调函数列表

**Comment by LiuLangTianYa** [comment]
自动绑组件和生成代码的，我抄了Deer_Gameframwork的自己改了一点，既然你也支持了，那就更好了

**Comment by LiuLangTianYa** [comment]
UGUI bundles的路径，会生成两次实体的bug，你改的代码没推送哦

**Comment by AlianBlank** [comment]
你需要更新 com.gameframex.unity.ui  和com.gameframex.unity.ui.ugui 到最新即可
