### ISSUE TITLE
【需求】希望增加GF自带Debugger组件

### ISSUE THREAD

**Issue by JaeyJiang** [GameFrameX/GameFrameX.Unity#6]
强烈希望增加这个作为可选插件.
这个组件在实际使用过程中, 可以非常方便地获取一些实时性能表现数据.
以及团队协同时, 能更方便从QA和策划那边获取一些设备信息.

**Comment by AlianBlank** [comment]
https://github.com/GameFrameX/com.gameframex.unity.debugger
