### ISSUE TITLE
【需求】UI求增加UGUI的支持包可以供替换FairyUI包

### ISSUE THREAD

**Issue by JaeyJiang** [GameFrameX/GameFrameX.Unity#7]
项目之前很多资产是基于UGUI的。几乎无法直接切换到FairyUI。急需支持这个。

**Comment by LiuLangTianYa** [comment]
UGUI框架啥时候支持啊

**Comment by AlianBlank** [comment]
已经在支持中了.

**Comment by LiuLangTianYa** [comment]
牛的，有个大概得时间节点么

**Comment by AlianBlank** [comment]
应该下周就能跑起来

**Comment by AlianBlank** [comment]
我需要用一个目包.驱动两套UI系统

**Comment by AlianBlank** [comment]
已经完整基础的适配
https://github.com/GameFrameX/com.gameframex.unity.ui
https://github.com/GameFrameX/com.gameframex.unity.ui.ugui
https://github.com/GameFrameX/com.gameframex.unity.ui.fairygui
