### ISSUE TITLE
【需求】FGUI的新增与卸载希望增加两个新的方法

### ISSUE THREAD

**Issue by JaeyJiang** [GameFrameX/GameFrameX.Unity#8]
1.  希望新增一个Add的重载函数能把已有的引用加入到UI节点上。 目前Remove是把UI界面从UI节点上移除了,但是并不会销毁.  后续这个引用只能用作调用Dispose和置空, 
2. 希望给Remove方法增加回调，OnRemove就行，因为Remove后，界面还在，有时候需要进行一些处理。
3. 希望新增一个Destroy方法，相当于Remove+Dispose

**Comment by AlianBlank** [comment]
OnRemove 暂时不做.等接口统一之后弄

**Comment by AlianBlank** [comment]
已经增加Dispose 函数接口和AddUI 接口. 请尽量使用异步接口.
