### ISSUE TITLE
【Bug】Sound组件问题，播放音频导致Unity直接卡死，没有报错

### ISSUE THREAD

**Issue by JaeyJiang** [GameFrameX/GameFrameX.Unity#9]
GameApp.Sound.PlaySound("Assets/Bundles/Sound/voice_bgm_lobby", "Music");

断点看过，是在加载成功资源以后卡主的。 
如果写一个没有的资源，加载失败不会卡主，会正常抛出异常

**Comment by AlianBlank** [comment]
经过我的测试.确定有卡死的问题.由于异步转同步导致的.
已经修复了
